.\"	$OpenBSD: trd.conf.5 $
.\"
.Dd $Mdocdate: May 1 2016 $
.Dt ACME-CLIENT.CONF 5
.Os
.Sh NAME
.Nm trd.conf
.Nd trd configuration file
.Sh DESCRIPTION
The
.Nm
config file is split into three columns, delimited by a single space:
.Bl -tag -width xxxx
.It Sy IP
Source IP address of the request.
.It Sy Requested File
File that the source IP is requesting.
.It Sy Rewrite File
File that the host should use instead of the requested file.
.El
.Pp
For example:
.Bd -literal -offset indent
10.33.0.12 /etc/boot.conf /i386/snapshots/boot.conf
10.33.0.12 /bsd /i386/snapshots/bsd.rd
.Ed
.Sh FILES
.Bl -tag -width "/etc/trd.conf" -compact
.It Pa /etc/trd.conf
.Xr trd 8
configuration file
.El
.Sh SEE ALSO
.Xr trd 8
